# Generated by Django 4.2.18 on 2025-01-22 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_type', models.CharField(default='Casual', max_length=10)),
                ('player1_name', models.CharField(default='Player 1', max_length=100)),
                ('player2_name', models.CharField(default='Player 2', max_length=100)),
                ('winner_name', models.CharField(default='Winner', max_length=100)),
                ('loser_name', models.CharField(default='Loser', max_length=100)),
                ('player1_streak', models.IntegerField(default=0)),
                ('player2_streak', models.IntegerField(default=0)),
                ('player1_casual_rank', models.IntegerField(default=0)),
                ('player2_casual_rank', models.IntegerField(default=0)),
                ('player1_tournament_rank', models.IntegerField(default=0)),
                ('player2_tournament_rank', models.IntegerField(default=0)),
                ('player1_goals', models.IntegerField(default=0)),
                ('player2_goals', models.IntegerField(default=0)),
                ('game_date', models.DateTimeField(auto_now_add=True)),
                ('game_played_time', models.FloatField(default=0)),
                ('loser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser_player', to=settings.AUTH_USER_MODEL)),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
