# Generated by Django 4.2.17 on 2025-01-09 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0004_alter_friend_receiver_alter_friend_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='sender',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='receiver',
            new_name='target',
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='block',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocker_social', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='block',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_social', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_social', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers_social', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('owner', 'target')},
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('owner', 'target')},
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('owner', 'target')},
        ),
        migrations.RemoveField(
            model_name='block',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='block',
            name='blocker',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
    ]
