# Generated by Django 4.2.17 on 2025-01-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
