# Generated by Django 4.2.17 on 2025-01-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='secret_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
