# Generated by Django 4.2.17 on 2025-01-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_uploadpp',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
