# Generated by Django 4.2.17 on 2025-01-07 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='blocked_users',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='friend_requests',
        ),
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
