# Generated by Django 4.2.17 on 2025-01-08 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by_customuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
